config/routes.rb
Rails.application.routes.draw do

  root 'movies#index'

  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:show, :create]

  get '/signup' => 'users#new'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

end

app/models/movie.rb
 class Movie < ActiveRecord::Base

  validates :title, :release_date, :genre, :director, :actors, presence: true

  validates :description, length: { minimum: 50 }, presence: true

  has_many :reviews

  belongs_to :creator, class_name: 'User'

  mount_uploader :poster, PosterUploader

  scope :now_playing, -> { where("release_date between ? and ?", Date.today - 1.month, Date.today) }

  scope :coming_soon, -> { where("release_date between ? and ?", Date.today + 1.day, Date.today + 1.month) }

  def now_playing
    release_date.between?(Date.today - 1.month, Date.today)
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

  validates :rating, :content, presence: true

  validates :content, length: { minimum: 6 }

  belongs_to :movie

  belongs_to :reviewer, class_name: 'User'

  # scope :recent, -> { order(created_at: :desc) }

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  before_save { self.email = email.downcase }

  validates :name, :email, presence: true

  validates :password, length: { minimum: 6 }

  has_many :created_movies, foreign_key: 'creator_id', class_name: 'Movie'

  has_many :reviewed_movies, foreign_key: 'reviewer_id', class_name: 'Review'

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

  

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_filter :set_movie, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate, except: [:index, :show]

  def index
    @now_playing = Movie.paginate(page: params[:page], per_page: 8).all.order('release_date DESC').now_playing
    render :json => @now_playing
    # @coming_soon = Movie.all.order('created_at DESC').coming_soon
  end

  def show
    @reviews = @movie.reviews.order('created_at DESC').paginate(page: params[:page], per_page: 6)
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = current_user.created_movies.build(movie_params)

    if @movie.save
      flash[:notice] = 'Movie Successfully Created'
      redirect_to movie_path(@movie)
    else
      flash.now[:alert] = 'Invalid Movie Form'
      render 'new'
    end
  end

  def edit

  end

  def update
    if @movie.update_attributes(movie_params)
      flash[:notice] = 'Movie Successfully Updated'
      redirect_to movie_path(@movie)
    else
      flash.now[:alert] = 'Invalid Movie Form'
      render 'edit'
    end      
  end

  def destroy
    @movie.destroy
    flash[:notice] = 'Movie Successfully Deleted'
    redirect_to root_path
  end


  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :release_date, :genre, :description, :director, :actors, :poster, :trailer)
  end

  def authenticate
    unless logged_in?
      flash[:alert] = 'You Must Log In First'
      redirect_to login_path
    end
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :authenticate

  def new
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.build
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.merge(current_user.reviewed_movies).create(review_params)
    # or you can do:
    # @review = @movie.reviews.build(review_params)
    # @review.reviewer = current_user
    # both do the trick!
    if @review.save
      flash[:notice] = 'Review Successfully Created'
      redirect_to movie_path(@movie)
    else
      flash.now[:alert] = 'Invalid Review Form'
      render 'new'
    end
  end


  private

  def review_params
    params.require(:review).permit(:rating, :content, :movie_id)
  end

  def authenticate
    unless logged_in?
      flash[:alert] = 'You Must Log In First'
      redirect_to login_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      flash[:notice] = 'Logged In'
      redirect_to user
    else
      flash.now[:alert] = 'Invalid Email/Password Combination'
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:notice] = 'Logged Out'
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :set_user, only: [:show, :edit, :update]

  def show

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:notice] = 'Signed Up'
      redirect_to user_path(@user)
    else
      flash.now[:alert] = 'Invalid Sign Up Form'
      render 'new'
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Profile Updated!'
      redirect_to user_path(@user)
    else
      flash.now[:alert] = 'Invalid Update Form'
      render 'edit'
    end
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper


end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # def redirect_to_back(default = user_path(user)) send them back to add movie page
  #   if !request.env["HTTP_REFERER"].blank? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
  #     redirect_to :back
  #   else
  #     redirect_to default
  #   end
  # end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Freshtomatoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header id="header">

  <span id="home_image"><%= link_to image_tag("tomato.jpg"), root_path %></span>
  <span id="add_movie_link"><%= link_to 'Add Movie', new_movie_path %></span>
  
  <% if logged_in? %>
    <span id="logout_link"><%= link_to 'Log Out', logout_path, method: :delete %></span>
    <span id="profile_link"><%= link_to 'Profile', current_user %></span>
  <% else %>
    <span id="signup_link"><%= link_to 'Sign Up', signup_path %></span>
    <span id="login_link"><%= link_to 'Log In', login_path %></span>
  <% end %>

</header>

<div id="notification">
  <% if flash[:notice] %>
      <div id="notice"><%= flash[:notice] %></div>
  <% elsif flash[:alert] %>
      <div id="alert"><%= flash[:alert] %></div>
  <% end %>
</div>


<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<% if @movie.errors.any? %>
<div id="errors_box">
  <h3>Please fix the following <%= pluralize(@movie.errors.count, 'error') %>:</h3>
  <ul>
    <% @movie.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
</div>

<div class="add_movie_form_box">
  <div id="add_movie_form">
    <h1 id="add_movie_h1"><%= yield(:title) %></h1>
    <%= form_for @movie do |f| %>


      <%= f.label :title %>:<br />
      <%= f.text_field :title, :class => 'form_field' %><br /><br />

      <%= f.label :genre %>:
      <%= f.text_field :genre, :class => 'form_field' %><br /><br />

      <%= f.label :director %>:
      <%= f.text_field :director, :class => 'form_field' %><br /><br />

      <%= f.label :actors %>:
      <%= f.text_field :actors, :class => 'form_field' %><br /><br />

      <%= f.label :trailer %>:<br />
      <%= f.text_field :trailer, :class => 'form_field' %><br /><br />

      <%= f.label :release_date %>:<br />
      <%= f.date_field :release_date, :class => 'form_release' %><br /><br />

      <%= f.label :poster %>:
      <%= f.file_field :poster, :class => 'form_poster' %><br /><br />

      <%= f.label :description %>:<br />
      <%= f.text_area :description, :class => 'form_description' %><br /><br />

      <%= f.submit 'Submit', :class => 'submit_button' %>

    <% end %>
  </div>
</div>

app/views/movies/edit.html.erb
<% provide(:title, @movie.title) %>

<%= render partial: 'form' %>

app/views/movies/index.html.erb
<div id="wrapper">
  <div id="now_playing_section">
    <h1 id="now_playing_header">Now Playing</h1>
      <% @now_playing.each do |movie| %>
        <div id="movie_poster_wrapper">
          <p id="movie_title_main_page"><%= movie.title %></p>
          <p id="movie_poster"><%= link_to image_tag(movie.poster_url, size: '250x250'), movie_path(movie) %></p>
          <p id="movie_poster_release"><%= movie.release_date.strftime('%b %d, %Y') %></p>
        </div>
      <% end %>
  </div>

  <span id="coming_soon_section">
    <h1 id="coming_soon_header">Coming Soon</h1>
      <% @coming_soon.each do |movie| %>
        <!-- cs = coming soon -->
        <div id="cs_each_movie"><%= link_to movie.title, movie_path(movie) %> - <%= movie.release_date.strftime('%b %d, %Y') %> </div><br />
      <% end %>
  </span>

<div class="digg_pagination"><%= will_paginate @now_playing %></div>

</div>

app/views/movies/new.html.erb
<% provide(:title, "New Movie") %>

<%= render partial: 'form' %>

app/views/movies/show.html.erb
<div id="show_page_container">
  <span><%= image_tag @movie.poster_url, size: '400x550' %></span>

  <div id="show_page_info">
    <span id="movie_title"><%= @movie.title + " " %></span> <span>(<%= @movie.release_date.strftime("%Y") %>)</span>

    <% if current_user && @movie.creator == current_user %>
    <div>
      <span id="edit_link">(<%= link_to 'Edit', edit_movie_path + " " %> |</span>
      <span id="delete_link"><%= link_to 'Delete', movie_path, method: :delete, data: { confirm: 'Are you sure?' } %>)</span>
    </div><br />
    <% end %>

    <p><i>Created By: <%= link_to @movie.creator.name, user_path(@movie.creator) %></i></p>
    <p>Release Date: <%= @movie.release_date.strftime("%B %e") %></p>
    <p>Genre: <%= @movie.genre %></p>
    <p><%= link_to 'Watch Trailer', @movie.trailer %></p>
    <p>Directed By: <%= @movie.director %></p>
    <p>Cast: <%= @movie.actors %></p>
    <p>Summary: <%= @movie.description %></p>
  </div>

</div>

  
<div id="review_wrapper">

  <% if @movie.now_playing %>
    <% if @reviews.any? %>
    <span id="review_heading">Reviews:</span>
    <% if current_user %>  
      <span id="add_review_heading"><%= link_to 'Add Review', new_movie_review_path(@movie) %></span>
    <% end %>
      
      <% @reviews.each do |review| %>
        <div id="each_review_container">
          <span><%= link_to review.reviewer.name, user_path(review.reviewer) %></span>
          <span id="time"><%= review.created_at.try(:strftime,'%b %d, %Y') %></span>
          <p>Rating: <%= review.rating %>/10</p>
          <p><%= review.content %></p>
        </div>
      <% end %>
      <div class="digg_pagination_reviews"><%= will_paginate @reviews %></div>
    <% else %>
      <span id="review_message">No Reviews yet!</span>
      <span id="add_new_review_link"><%= link_to 'Add New Review', new_movie_review_path(@movie) %></span>
    <% end %>
  <% else %>
    <p id="review_message">You will be able to submit a review when the movie releases</p>
  <% end %>

</div>

app/views/reviews/new.html.erb
<%= form_for([@movie, @review]) do |f| %>
<div id="errors_box">
  <% if @review.errors.any? %>

    <h3>Please fix the following <%= pluralize(@review.errors.count, 'error') %>:</h3>

    <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<div id="add_review_form_box">
  <div id="add_review_form">
  <h1 id="add_review_h1">Add Review</h1>

    <%= f.label :rating %>:<br />
    <%= f.number_field :rating, min: 1, max: 10, :class => 'rating_field' %><br /><br />

    <%= f.label :content %>:<br />
    <%= f.text_area :content, :class => 'form_description' %><br /><br />

    <%= f.submit 'Submit', :class => 'submit_button' %>

<% end %>

app/views/users/new.html.erb
  <% if @user.errors.any? %>
  <div id="errors_box">
    <h3>Please fix the following <%= pluralize(@user.errors.count, 'error')%>:</h3>
         
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
       
  <% end %>
  </div>
  
<div class="signup_form_box">
  <div id="signup_form">
    <h1 id="signup_h1">Sign Up</h1>


    <%= form_for @user do |f| %>

      <%= f.label :name %>:<br />
      <%= f.text_field :name, :class => 'form_field' %><br /><br />

      <%= f.label :email %>:<br />
      <%= f.email_field :email, :class => 'form_field' %><br /><br />

      <%= f.label :password %>:<br />
      <%= f.password_field :password, :class => 'form_field' %><br /><br />

      <%= f.label :password_confirmation %>:<br />
      <%= f.password_field :password_confirmation, :class => 'form_field' %><br /><br />

      <%= f.submit 'Submit', :class => 'submit_button' %><br /><br />

    <% end %>

    <span>Already Registered? <%= link_to 'Log In', login_path %></span>
  </div>  

</div>

app/views/users/show.html.erb
<h1 id="user_profile_heading"><%= @user.name %>'s Profile</h1>

<div id="movies_created_wrapper">
  <span id="movies_created_heading">Movies Created:</span>
  <% if @user.created_movies.any? %>
    <% @user.created_movies.each do |movie| %>
      <p><%= link_to movie.title, movie_path(movie) %></p>
    <% end %>
  <% else %>
    <p><i>No Movies Created</i></p>
  <% end %>
</div>

<hr id="hr">

<div id="movies_reviewed_wrapper">
  <span id="reviews_created_heading">Reviews Created:</span>

  <% if @user.reviewed_movies.any? %>
    <% @user.reviewed_movies.each do |review| %>
    <div id="each_review_container">
      <span><%= review.movie.title %> | </span>
            <span id="time"><%= review.created_at.try(:strftime,'%b %d, %Y') %></span>
      <p>Rating:  <%= review.rating %>/10</p>
      <p><%= review.content %></p>
    </div>
    <% end %>
  <% else %>
    <p><i>No Reviews Created</i></p>
  <% end %>
</div>